apps/auth/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'auth'

url_password_reset = {
    'template_name': 'shop/auth/password/send_email.html',
    'email_template_name': 'shop/auth/password/reset_email.html'
}
url_password_done = {
    'template_name': 'shop/auth/password/reset_done.html'
}
url_password_confirm = {
    'template_name': 'shop/auth/password/reset_confirm.html'
}
url_done = {
    'template_name': 'shop/auth/password/reset_complete.html'
}
urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='shop/auth/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(next_page='/'),
         name='logout'),
    path('reset/password/',
         auth_views.PasswordResetView.as_view(
             email_template_name='shop/auth/password/reset_email.html',
             html_email_template_name='shop/auth/password/reset_email.html',
             template_name='shop/auth/password/send_email.html',
             success_url=reverse_lazy('auth:password_reset_done'),
         ),
         name='password_reset'),
    path('reset/password_done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name='shop/auth/password/reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='shop/auth/password/reset_confirm.html',
             success_url=reverse_lazy('auth:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='shop/auth/password/reset_complete.html'),
         name='password_reset_complete'),
]

apps/carts/urls.py
from django.urls import path
from .views import (
    add_cart,
    CartTemplateView
)

app_name = 'carts'

urlpatterns = [
    path('cart/', CartTemplateView.as_view(), name='list'),
    path('add_cart', add_cart, name='add_cart'),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ProfileTemplateView, create, WishListTemplateView

app_name = 'users'

urlpatterns = [
    path('profile/', login_required(ProfileTemplateView.as_view()), name='profile'),
    path('wish_list/', login_required(WishListTemplateView.as_view()), name='wish_list'),
    path('create/', create, name='create'),
]

gshop/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(r'', include('apps.web.urls', namespace='web')),
    path(r'', include('apps.products.urls', namespace='products')),
    path(r'', include('apps.users.urls', namespace='users')),
    path(r'', include('apps.carts.urls', namespace='carts')),
    path(r'', include('apps.auth.urls', namespace='auth')),
    url(r'^froala_editor/', include('froala_editor.urls')),
    url('', include('social_django.urls', namespace='social')),
]

apps/carts/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.products.models import Product


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='carts',
        on_delete=models.CASCADE
    )
    products = models.ManyToManyField(
        Product,
        related_name='products',
        blank=True,
    )
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(max_length=100, default='')
    phone = models.IntegerField(default=0)


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class Registrationform(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super(Registrationform, self).save(commit=False)
        user.first_name = cleaned_data['first_name']
        user.last_name = cleaned_data['last_name']
        user.email = cleaned_data['email']

        if commit:
            user.save()

        return user

# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#     fields = ('description', 'city', 'website', 'phone')

apps/carts/views.py
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.db.models import Sum
from apps.products.models import Product
from .models import Cart


class CartTemplateView(TemplateView):
    template_name = 'shop/users/cart.html'

    def get_context_data(self, **kwargs):
        context = super(CartTemplateView, self).get_context_data(**kwargs)
        user = self.request.user
        context['active_cart'] = True
        context['cart'] = Cart.objects.get(user=user)
        context['products'] = Cart.objects.filter(user=user).aggregate(subtotal=Sum('products__price'))

        return context


def add_cart(request):
    user_email = request.GET.get('user_email')
    product = request.GET.get('product')

    user = User.objects.get(email=user_email)
    product = Product.objects.get(slug=product)

    cart = Cart.objects.get(user=user)

    if not cart:
        cart = Cart(user=user)
        cart.save()
        cart.products.add(product.id)
    else:
        cart.products.add(product.id)

    data = {'msg': 'added product'}

    return JsonResponse(data)

apps/users/views.py
from django.views.generic import TemplateView
from django.shortcuts import redirect, HttpResponseRedirect, render
from .forms import Registrationform


class ProfileTemplateView(TemplateView):
    template_name = 'shop/users/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileTemplateView, self).get_context_data(**kwargs)
        context['active_profile'] = True
        return context


class WishListTemplateView(TemplateView):
    template_name = 'shop/users/wish_list.html'

    def get_context_data(self, **kwargs):
        context = super(WishListTemplateView, self).get_context_data(**kwargs)
        context['active_wishlist'] = True
        query = self.request.user.products.all()
        for dd in query:
            print (dd.product.name, '############')
        return context


def create(request):
    if request.method == 'POST':
        form = Registrationform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
        else:
            data = {'form': form}
            return render(request, 'shop/users/profile.html', data)

templates/shop/users/cart.html
{% extends "shop/layouts/base.html" %}

{% load static %}

{% block content %}
<!-- Page Title-->
<div class="page-title">
  <div class="container">
    <div class="column">
      <h1>My Wishlist</h1>
    </div>
    <div class="column">
      <ul class="breadcrumbs">
        <li>
          <a href="index.html">Home</a>
        </li>
        <li class="separator">&nbsp;</li>
        <li>
          <a href="account-orders.html">Account</a>
        </li>
        <li class="separator">&nbsp;</li>
        <li>My Wishlist</li>
      </ul>
    </div>
  </div>
</div>
<!-- Page Content-->
<div class="container padding-bottom-3x mb-2">
  <div class="row">
    <div class="col-lg-4">
      {% include 'shop/users/navbar.html' %}
    </div>
    <div class="col-lg-8">
      <div class="padding-top-2x mt-2 hidden-lg-up"></div>
      <!-- Wishlist Table-->
      <div class="table-responsive wishlist-table margin-bottom-none">
        <table class="table">
          <thead>
          <tr>
            <th>Subtotal:  {{ products.subtotal }}</th>
            <th class="text-center">
              <a class="btn btn-sm btn-outline-primary" href="#">
                Pay Paypal
              </a>
            </th>
          </tr>
          </thead>
          <tbody>
          {% for product in cart.products.all %}
          <tr>
            <td>
              <div class="product-item">
                <a class="product-thumb" href="{{ product.get_absolute_url }}" target="_blank">
                  <img src="{{ product.image }}" alt="Product">
                </a>
                <div class="product-info">
                  <h4 class="product-title">
                    <a href="{{ product.get_absolute_url }}" target="_blank">{{ product.name }}</a>
                  </h4>
                  <div class="text-lg text-medium text-muted">${{ product.price }}</div>
                  <div>Availability:
                    <div class="d-inline text-success">In Stock</div>
                  </div>
                </div>
              </div>
            </td>
            <td class="text-center">
              <a class="remove-from-cart" href="#" data-toggle="tooltip" title="Remove item">
                <i class="icon-cross"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/shop/users/login.html
{% extends "shop/layouts/base.html" %}

{% block content %}
<!-- Page Title-->
<div class="page-title">
   <div class="container">
      <div class="column">
         <h1>My Profile</h1>
      </div>
   </div>
</div>
<!-- Container-->
<div class="container padding-bottom-3x mb-2">
   <div class="row">
      <div class="col-md-6">
         <form class="login-box" method="post" action="{% url 'auth:login' %}">
            {% csrf_token %}
            <div class="row margin-bottom-1x">
               <div class="col-xl-4 col-md-6 col-sm-4">
                  <a class="btn btn-sm btn-block facebook-btn" href="#">
                     <i class="socicon-facebook"></i>&nbsp;Facebook login
                  </a>
               </div>
               <div class="col-xl-4 col-md-6 col-sm-4">
                  <a class="btn btn-sm btn-block twitter-btn" href="#">
                     <i class="socicon-twitter"></i>&nbsp;Twitter login
                  </a>
               </div>
               <div class="col-xl-4 col-md-6 col-sm-4">
                  <a class="btn btn-sm btn-block google-btn" href="{% url 'social:begin' 'google-oauth2' %}">
                     <i class="socicon-googleplus"></i>&nbsp;Google+ login
                  </a>
               </div>
            </div>
            <h4 class="margin-bottom-1x">Or using form below</h4>
            <div class="form-group input-group">
               <input class="form-control" type="text" placeholder="Email" name="username" required>
               <span class="input-group-addon"><i class="icon-mail"></i></span>
            </div>
            <div class="form-group input-group">
               <input class="form-control" type="password" placeholder="Password" name="password" required>
               <span class="input-group-addon"><i class="icon-lock"></i></span>
            </div>
            <div class="d-flex flex-wrap justify-content-between padding-bottom-1x">
               <label class="custom-control custom-checkbox">
                  <input class="custom-control-input" type="checkbox" checked>
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Remember me</span>
               </label><a class="navi-link" href="account-password-recovery.html">Forgot password?</a>
            </div>
            <div class="text-center text-sm-right">
               <button class="btn btn-primary margin-bottom-none" type="submit">Login</button>
            </div>
         </form>
      </div>
      <div class="col-md-6">
         <div class="padding-top-3x hidden-md-up"></div>
         <h3 class="margin-bottom-1x">No Account? Register</h3>
         <p>Registration takes less than a minute but gives you full control over your orders.</p>
         <form class="row" method="post">
            <div class="col-sm-6">
               <div class="form-group">
                  <label for="reg-fn">First Name</label>
                  <input class="form-control" type="text" id="reg-fn" required>
               </div>
            </div>
            <div class="col-sm-6">
               <div class="form-group">
                  <label for="reg-ln">Last Name</label>
                  <input class="form-control" type="text" id="reg-ln" required>
               </div>
            </div>
            <div class="col-sm-6">
               <div class="form-group">
                  <label for="reg-email">E-mail Address</label>
                  <input class="form-control" type="email" id="reg-email" required>
               </div>
            </div>
            <div class="col-sm-6">
               <div class="form-group">
                  <label for="reg-phone">Phone Number</label>
                  <input class="form-control" type="text" id="reg-phone" required>
               </div>
            </div>
            <div class="col-sm-6">
               <div class="form-group">
                  <label for="reg-pass">Password</label>
                  <input class="form-control" type="password" id="reg-pass" required>
               </div>
            </div>
            <div class="col-sm-6">
               <div class="form-group">
                  <label for="reg-pass-confirm">Confirm Password</label>
                  <input class="form-control" type="password" id="reg-pass-confirm" required>
               </div>
            </div>
            <div class="col-12 text-center text-sm-right">
               <button class="btn btn-primary margin-bottom-none" type="submit">Register</button>
            </div>
         </form>
      </div>
   </div>
</div>
{% endblock %}

templates/shop/users/navbar.html
<aside class="user-info-wrapper">
   <div class="user-cover" style="background-image: url(img/account/user-cover-img.jpg);">
   </div>
   <div class="user-info">
      <div class="user-avatar">
         <a class="edit-avatar" href="#"></a>
         <img src="img/account/user-ava.jpg" alt="User">
      </div>
      <div class="user-data">
         <h4>Daniel Adams</h4>
         <span>Joined February 06, 2017</span>
      </div>
   </div>
</aside>
<nav class="list-group">
   <a class="list-group-item with-badge {% if active_cart %} active {% endif %}" href="{% url 'carts:list' %}">
      <i class="icon-bag"></i>Cart
      <span class="badge badge-primary badge-pill">6</span>
   </a>
   <a class="list-group-item {% if active_profile %} active {% endif %}" href="{% url 'users:profile' %}">
      <i class="icon-head"></i>Profile
   </a>
   <a class="list-group-item" href="account-address.html">
      <i class="icon-map"></i>Addresses
   </a>
   <a class="list-group-item with-badge {% if active_wishlist %} active {% endif %}" href="{% url 'users:wish_list' %}">
      <i class="icon-heart"></i>Wishlist
      <span class="badge badge-primary badge-pill">{{ request.user.products.count }}</span>
   </a>
   <a class="list-group-item with-badge" href="account-tickets.html">
      <i class="icon-tag"></i>My Tickets
      <span class="badge badge-primary badge-pill">4</span>
   </a>
</nav>

templates/shop/users/profile.html
{% extends "shop/layouts/base.html" %}

{% load static %}

{% block content %}
<!-- Page Title-->
<div class="page-title">
   <div class="container">
      <div class="column">
         <h1>My Profile</h1>
      </div>
      <div class="column">
         <ul class="breadcrumbs">
            <li><a href="index.html">Home</a></li>
            <li class="separator">&nbsp;</li>
            <li><a href="account-orders.html">Account</a></li>
            <li class="separator">&nbsp;</li>
            <li>My Profile</li>
         </ul>
      </div>
   </div>
</div>
<!-- Page Content-->
<div class="container padding-bottom-3x mb-2">
   <div class="row">
      <div class="col-lg-4">
         {% include 'shop/users/navbar.html' %}
      </div>
      <div class="col-lg-8">
         <div class="padding-top-2x mt-2 hidden-lg-up"></div>
         <form class="row">
            <div class="col-md-6">
               <div class="form-group">
                  <label for="account-fn">First Name</label>
                  <input class="form-control" type="text" id="account-fn" value="{{ request.user.first_name }}" required>
               </div>
            </div>
            <div class="col-md-6">
               <div class="form-group">
                  <label for="account-ln">Last Name</label>
                  <input class="form-control" type="text" id="account-ln" value="{{ request.user.last_name }}" required>
               </div>
            </div>
            <div class="col-md-6">
               <div class="form-group">
                  <label for="account-email">E-mail Address</label>
                  <input class="form-control" type="email" id="account-email" value="{{ request.user.email }}" disabled>
               </div>
            </div>
            <div class="col-md-6">
               <div class="form-group">
                  <label for="account-phone">Phone Number</label>
                  <input class="form-control" type="text" id="account-phone" value="+7(805) 348 95 72" required>
               </div>
            </div>
            <div class="col-md-6">
               <div class="form-group">
                  <label for="account-pass">New Password</label>
                  <input class="form-control" type="password" id="account-pass">
               </div>
            </div>
            <div class="col-md-6">
               <div class="form-group">
                  <label for="account-confirm-pass">Confirm Password</label>
                  <input class="form-control" type="password" id="account-confirm-pass">
               </div>
            </div>
            <div class="col-12">
               <hr class="mt-2 mb-3">
               <div class="d-flex flex-wrap justify-content-between align-items-center">
                  <label class="custom-control custom-checkbox d-block">
                     <input class="custom-control-input" type="checkbox" checked>
                     <span class="custom-control-indicator"></span>
                     <span class="custom-control-description">Subscribe me to Newsletter</span>
                  </label>
                  <button class="btn btn-primary margin-right-none" type="button" data-toast data-toast-position="topRight" data-toast-type="success" data-toast-icon="icon-circle-check" data-toast-title="Success!" data-toast-message="Your profile updated successfuly.">Update Profile</button>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>
{% endblock %}

templates/shop/users/wish_list.html
{% extends "shop/layouts/base.html" %}

{% load static %}

{% block content %}
<!-- Page Title-->
<div class="page-title">
  <div class="container">
    <div class="column">
      <h1>My Wishlist</h1>
    </div>
    <div class="column">
      <ul class="breadcrumbs">
        <li>
          <a href="index.html">Home</a>
        </li>
        <li class="separator">&nbsp;</li>
        <li>
          <a href="account-orders.html">Account</a>
        </li>
        <li class="separator">&nbsp;</li>
        <li>My Wishlist</li>
      </ul>
    </div>
  </div>
</div>
<!-- Page Content-->
<div class="container padding-bottom-3x mb-2">
  <div class="row">
    <div class="col-lg-4">
      {% include 'shop/users/navbar.html' %}
    </div>
    <div class="col-lg-8">
      <div class="padding-top-2x mt-2 hidden-lg-up"></div>
      <!-- Wishlist Table-->
      <div class="table-responsive wishlist-table margin-bottom-none">
        <table class="table">
          <thead>
          <tr>
            <th>Product Name</th>
            <th class="text-center"><a class="btn btn-sm btn-outline-danger" href="#">Clear Wishlist</a></th>
          </tr>
          </thead>
          <tbody>
          {% for wish_list in request.user.products.all %}
          <tr>
            <td>
              <div class="product-item">
                <a class="product-thumb" href="{{ wish_list.product.get_absolute_url }}" target="_blank">
                  <img src="{{ wish_list.product.image }}" alt="Product">
                </a>
                <div class="product-info">
                  <h4 class="product-title">
                    <a href="{{ wish_list.product.get_absolute_url }}" target="_blank">{{ wish_list.product.name }}</a>
                  </h4>
                  <div class="text-lg text-medium text-muted">${{ wish_list.product.price }}</div>
                  <div>Availability:
                    <div class="d-inline text-success">In Stock</div>
                  </div>
                </div>
              </div>
            </td>
            <td class="text-center">
              <a class="remove-from-cart" href="#" data-toggle="tooltip" title="Remove item">
                <i class="icon-cross"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <hr class="mb-4">
      <label class="custom-control custom-checkbox d-block">
        <input class="custom-control-input" type="checkbox" checked>
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">Inform me when item from my wishlist is available</span>
      </label>
    </div>
  </div>
</div>
{% endblock %}